Repository InseeFrLab/onyxia-api, pull requests merged in 2024-11, with the labels that each got.

#498 overwrite schema based on roles
  docs/region-configuration.md
  onyxia-api/src/main/java/fr/insee/onyxia/api/configuration/CustomObjectMapper.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/api/mylab/MyLabController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/api/mylab/QuotaController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/pub/CatalogController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/pub/JsonSchemaController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/dao/universe/CatalogLoader.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/security/OIDCConfiguration.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/JsonSchemaRegistryService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/JsonSchemaResolutionService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/kubernetes/KubernetesService.java
  onyxia-api/src/main/resources/application.properties
  onyxia-api/src/main/resources/regions.json
  onyxia-api/src/main/resources/schemas/nodeSelector-gpu.json
  onyxia-api/src/main/resources/schemas/nodeSelector.json
  onyxia-api/src/main/resources/schemas/tolerations.json
  onyxia-model/src/main/java/fr/insee/onyxia/model/User.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/catalog/CatalogWrapper.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/catalog/Pkg.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/region/Region.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/views/Views.java
Labels: documentation

#515 Add roles claim documentation
  README.md
Labels: documentation

#516 Refactor catalog refresh to make it more resilient
  onyxia-api/src/main/java/fr/insee/onyxia/api/Application.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/dao/universe/CatalogRefresher.java
  onyxia-api/src/test/java/fr/insee/onyxia/api/dao/universe/CatalogRefresherTest.java
Labels: bug

#524 Cleanup : remove unused region geo location
  docs/region-configuration.md
  onyxia-api/src/main/resources/regions.json
  onyxia-model/src/main/java/fr/insee/onyxia/model/region/Region.java
Labels: documentation

#530 Bump helm version to v3.16.3
  onyxia-api/install-helm.sh
Labels: dependencies
