Repository InseeFrLab/onyxia-api, pull requests merged in 2024-07, with the labels that each got.

#457 Fix service status retrieval
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmReleaseHealthResolver.java
Labels: bug

#459 openshift scc support
  docs/region-configuration.md
  onyxia-model/src/main/java/fr/insee/onyxia/model/region/Region.java
Labels: enhancement

#461 Bump helm to v3.15.3
  onyxia-api/Dockerfile
Labels: dependencies
