Repository InseeFrLab/onyxia-api, pull requests merged in 2024-02, with the labels that each got.

#373 Add labeler
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/labeler.yml
Labels: ci

#376 Fix release drafter
  .github/workflows/release-drafter.yml
Labels: bug, ci

#377 Release drafter : fix version
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/labeler.yml
Labels: ci

#372 Typos
  onyxia-model/src/main/java/fr/insee/onyxia/model/dto/CreateServiceDTO.java
Labels: documentation

#378 OIDC : extra params
  README.md
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/pub/ConfigurationController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/security/OIDCConfiguration.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/region/Region.java
Labels: enhancement

#379 Fix : make OIDC extra query params optional
  onyxia-api/src/main/resources/application.properties
Labels: bug

#384 Bump helm version to v3.14.0
  onyxia-api/Dockerfile
Labels: dependencies

#389 Bump Helm to patch 3.14.1
  onyxia-api/Dockerfile
Labels: dependencies

#392 Fix swagger auth
  onyxia-api/src/main/java/fr/insee/onyxia/api/openapi/OpenApiConfiguration.java
Labels: bug

#393 Revert org.apache.commons:commons-compress v1.26.0
  onyxia-api/pom.xml
Labels: dependencies

#395 Fix swagger auth
  onyxia-api/src/main/java/fr/insee/onyxia/api/openapi/OpenApiConfiguration.java
Labels: bug

#388 Helm : list all releases
  helm-wrapper/src/main/java/io/github/inseefrlab/helmwrapper/service/HelmInstallService.java
  helm-wrapper/src/test/java/io/github/inseefrlab/helmwrapper/UtilsCommandTest.java
Labels: helm-wrapper

#397 Use a less worrying emoji for testing label
  .github/release-drafter.yml
Labels: ci
