Repository InseeFrLab/onyxia-api, pull requests merged in 2024-06, with the labels that each got.

#424 Create a secret for Onyxia's services configuration
  helm-wrapper/src/main/java/io/github/inseefrlab/helmwrapper/service/HelmInstallService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/api/mylab/MyLabController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/AppsService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/kubernetes/KubernetesService.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/dto/CreateServiceDTO.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/service/Service.java
Labels: enhancement

#432 Fix secret reading
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/kubernetes/KubernetesService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/utils/Base64Utils.java
Labels: bug

#431 Fix suspend / resume
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/api/mylab/MyLabController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/AppsService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java
Labels: bug

#438 Downgrade fabric8 to 6.12.0
  pom.xml
Labels: dependencies

#429 Add namespace metadata
  docs/region-configuration.md
  onyxia-api/src/main/java/fr/insee/onyxia/api/controller/api/onboarding/OnboardingController.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/kubernetes/KubernetesService.java
  onyxia-api/src/main/resources/regions.json
  onyxia-api/src/test/java/fr/insee/onyxia/api/controller/api/onboarding/OnboardingControllerTest.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/region/Region.java
Labels: enhancement

#441 Refactor and merge test classes for Command class
  helm-wrapper/src/main/java/io/github/inseefrlab/helmwrapper/utils/Command.java
  helm-wrapper/src/test/java/io/github/inseefrlab/helmwrapper/UtilsCommandTest.java
  helm-wrapper/src/test/java/io/github/inseefrlab/helmwrapper/utils/CommandTest.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/dao/universe/CatalogRefresher.java
Labels: helm-wrapper

#447 Revert "Refactor and merge test classes for Command class (#441)"
  helm-wrapper/src/main/java/io/github/inseefrlab/helmwrapper/utils/Command.java
  helm-wrapper/src/test/java/io/github/inseefrlab/helmwrapper/UtilsCommandTest.java
  helm-wrapper/src/test/java/io/github/inseefrlab/helmwrapper/utils/CommandTest.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/dao/universe/CatalogRefresher.java
Labels: helm-wrapper

#448 Fix NPE in get package by name
  onyxia-model/src/main/java/fr/insee/onyxia/model/catalog/CatalogWrapper.java
Labels: bug

#428 Return the list of controllers to better determine service's health
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java
  onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmReleaseHealthResolver.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/service/HealthCheckResult.java
  onyxia-model/src/main/java/fr/insee/onyxia/model/service/Service.java
Labels: enhancement
